#pragma config(Sensor, in1,    potR,           sensorPotentiometer)
#pragma config(Sensor, dgtl2,  quad,           sensorQuadEncoder)
#pragma config(Sensor, dgtl4,  quad2,          sensorQuadEncoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int integral = 0;
	int prevError = 0;
	while(true)
	{
		if (vexRT[Btn6U] == 1)
		{
			motor[port2] = 127;
		}
		else
		{
			motor[port2] = 0;
		}
		int setpoint = SensorValue[quad2];
		int error = setpoint - SensorValue[quad];
		integral += error;
		int derivative = error - prevError;
		prevError = error;
		motor[port1] = error*4 + integral*0 + derivative*6;
		wait1Msec(1);

	}
}
