#pragma config(Sensor, dgtl2,  quadA,          sensorQuadEncoder)
#pragma config(Sensor, dgtl4,  quadB,          sensorQuadEncoder)
#pragma config(Motor,  port2,           motorA,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           motorB,        tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int integralA = 0;
	int prevErrorA = 0;
	int integralB = 0;
	int prevErrorB = 0;
	int CorrectionCounter = 0;
	SensorValue[quadA] = 0;
	SensorValue[quadB] = 0;
	while(true)
	{
		if (vexRT[Btn6U] == 1)
		{
			CorrectionCounter += 1;
		}
		else if (vexRT[Btn6D] == 1)
		{
			CorrectionCounter -= 1;
		}
		else
		{
			CorrectionCounter = CorrectionCounter;
		}
		int errorA = CorrectionCounter - SensorValue[quadA];
		int errorB = CorrectionCounter - SensorValue[quadB];
		integralA += errorA;
		integralB += errorB;
		int derivativeA = errorA - prevErrorA;
		int derivativeB = errorB - prevErrorB;
		prevErrorA = errorA;
		prevErrorB = errorB;
		motor[motorA] = errorA*0 + integralA*0 + derivativeA*0;
		motor[motorB] = errorB*0 + integralB*0 + derivativeB*0;
		wait1Msec(1);
	}
}
